### PR TITLE
WIP: Create Modal in react

### LINKED ISSUE #15: Create Modal in react
_Detailed description about functionality will be available in README file with 1st commit of PR associated_

### PR DESCRIPTION
**Pull request by 1akshat**
Modal implementation in React From Scratch.

- [x] Main Component
- [x] Modal Component
- [x] Toggle Component
- [ ] Modal Style Component
- [x] Button Component
- [x] Modal Basic Design With Overlay
- [x] 'ESC' key event handling
- [x] Close Modal on click in overlay area
- [x] First field auto-focus
- [x] Focus should not go away from modal, when modal is opened
- [x] After close, focus should go back to former element, from where action of modal started
- [x] Add Tests

Break down of functionalities/features into details - https://docs.google.com/document/d/1NDbDCa__Syebq2QSUVNth1oJ0pZbIlqJXNTNzLByzms/edit?usp=sharing

### CODE REVIEW

**Review by 1akshat — COMMENTED** [review]
8f7ca69 Why did you check in this file @varora1406 ? I don't think there is a requirement for this file to be committed.

**Review by ArfatSalman — CHANGES_REQUESTED** [review]
Indentation does not match in all files.

**Comment by 1akshat** [comment]
> Indentation does not match in all files.

Will fix that @ArfatSalman.

**Comment by 1akshat** [comment]
### WIP modal demo till now:

captured

Handled Events:

- [x] Esc Key Close
- [x] Overlay Area Close
- [x] Tabbble Fields

**Comment by vaibhavarora14** [comment]
> 
> 
> [8f7ca69](https://github.com/pesto-students/deep-dive-varora1406/commit/8f7ca69f69b5ecc03770dde2c58e88ec330d08e5) Why did you check in this file @varora1406 ? I don't think there is a requirement for this file to be committed.

@1akshat , I believe it should be submitted.
A detailed reasoning by npm is available at - https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md

**Comment by 1akshat** [comment]
### Modal Progress Demo:
captured (1)

- [x] Handle Focus Trap.

**Pull request closed without merging**
